[project]
name = "gy4027"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter-book>=2.1.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
